/**
 * PDF Generation Module
 *
 * Generates comprehensive, professional PDF reports of typing test results
 * with detailed metrics, scoring breakdown, and recommendations
 */

import jsPDF from 'jspdf';
import { TestConfig, TestState } from '../types';

export async function generateResultPDF(
  _resultElementId: string,
  testConfig: TestConfig,
  testState: TestState
): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  
  let currentY = margin;
  const testDate = new Date();
  const sessionId = `ST-${testDate.getTime().toString(36).toUpperCase()}`;

  // Helper functions
  const addPageNumber = (pageNum: number) => {
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 10);
  };

  const addFooter = () => {
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by SarkariType – https://kostubh.github.io/sarkari_type/', margin, pageHeight - 10);
    pdf.setFontSize(7);
    pdf.text('This report is auto-generated and summarizes observed typing performance for the specified session.', margin, pageHeight - 6);
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (currentY + requiredSpace > pageHeight - 30) {
      addFooter();
      addPageNumber(pdf.internal.pages.length - 1);
      pdf.addPage();
      currentY = margin;
      return true;
    }
    return false;
  };

  const addSectionTitle = (title: string, size = 14) => {
    checkPageBreak(15);
    pdf.setFontSize(size);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 102, 204);
    pdf.text(title, margin, currentY);
    currentY += size === 14 ? 8 : 10;
  };

  const addKeyValuePair = (key: string, value: string) => {
    checkPageBreak(6);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(60, 60, 60);
    pdf.text(key + ':', margin, currentY);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(0, 0, 0);
    pdf.text(value, margin + 60, currentY);
    currentY += 6;
  };

  // ============ PAGE 1: EXECUTIVE SUMMARY ============
  
  // Title Block
  pdf.setFillColor(0, 102, 204);
  pdf.rect(0, 0, pageWidth, 45, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('OFFICIAL TYPING PERFORMANCE REPORT', pageWidth / 2, 20, { align: 'center' });
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by SarkariType – Master Your Typing Skills', pageWidth / 2, 30, { align: 'center' });
  pdf.setFontSize(9);
  pdf.text(`Session ID: ${sessionId}`, pageWidth / 2, 38, { align: 'center' });
  
  currentY = 55;
  
  // Candidate & Session Details
  addSectionTitle('Candidate & Session Details', 14);
  addKeyValuePair('Candidate', 'Anonymous User');
  addKeyValuePair('Test Date', testDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }));
  addKeyValuePair('Test Time', testDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }));
  addKeyValuePair('Session Duration', `${testState.elapsedSeconds.toFixed(1)} seconds`);
  currentY += 5;

  // Key Performance Indicators
  addSectionTitle('Key Performance Indicators', 14);
  
  const metrics = [
    { label: 'WPM', value: testState.wpm.toFixed(1), desc: 'Words per minute – speed of correctly typed content' },
    { label: 'Accuracy', value: `${testState.accuracy.toFixed(1)}%`, desc: 'Character-level accuracy across the full passage' },
    { label: 'Final Score', value: testState.finalScore.toFixed(1), desc: 'Composite score combining speed and accuracy' },
    { label: 'Duration', value: `${testState.elapsedSeconds.toFixed(1)}s`, desc: 'Effective active typing duration' },
  ];

  const boxWidth = (contentWidth - 10) / 2;
  const boxHeight = 25;
  let boxX = margin;
  let boxY = currentY;

  metrics.forEach((metric, index) => {
    if (index === 2) {
      boxX = margin;
      boxY += boxHeight + 5;
    }
    
    // Draw box
    pdf.setDrawColor(0, 102, 204);
    pdf.setLineWidth(0.5);
    pdf.rect(boxX, boxY, boxWidth, boxHeight);
    
    // Value
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 102, 204);
    pdf.text(metric.value, boxX + boxWidth / 2, boxY + 10, { align: 'center' });
    
    // Label
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    pdf.text(metric.label, boxX + boxWidth / 2, boxY + 16, { align: 'center' });
    
    // Description
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    const descLines = pdf.splitTextToSize(metric.desc, boxWidth - 4);
    pdf.text(descLines, boxX + boxWidth / 2, boxY + 20, { align: 'center' });
    
    boxX += boxWidth + 5;
  });
  
  currentY = boxY + boxHeight + 10;

  // Test Configuration
  addSectionTitle('Test Configuration', 14);
  
  // Configuration table
  const configData = [
    ['Time Mode', testConfig.timeMode === 'timed' ? 'Timed' : 'Timeless'],
    ['Allotted Time', testConfig.timeMode === 'timed' ? `${testConfig.duration} minute(s)` : 'N/A'],
    ['Text Source', testConfig.textSource.toUpperCase()],
    ['Word Count Target', `${testConfig.wordCount} words`],
    ['Display Settings', `Font: ${testConfig.displaySettings.fontSize}, Contrast: ${testConfig.displaySettings.contrast}`],
  ];

  configData.forEach(([key, value]) => {
    checkPageBreak(8);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 60);
    pdf.text(key, margin + 5, currentY);
    pdf.setTextColor(0, 0, 0);
    pdf.text(value, margin + 65, currentY);
    currentY += 6;
  });

  addFooter();
  addPageNumber(1);

  // ============ PAGE 2: DETAILED ACCURACY & ERRORS ============
  pdf.addPage();
  currentY = margin;

  addSectionTitle('Detailed Accuracy & Error Analysis', 16);
  currentY += 3;

  // Character-level statistics
  addSectionTitle('Character-Level Statistics', 12);
  
  const totalChars = testState.correctChars + testState.incorrectChars + testState.missedChars + testState.extraChars;
  
  const charStats = [
    ['Total Characters', totalChars.toString()],
    ['Correct Characters', testState.correctChars.toString()],
    ['Incorrect Characters', testState.incorrectChars.toString()],
    ['Missed Characters', testState.missedChars.toString()],
    ['Extra Characters', testState.extraChars.toString()],
  ];

  // Draw table
  const colWidth = contentWidth / 2;
  const rowHeight = 8;

  // Header
  pdf.setFillColor(0, 102, 204);
  pdf.rect(margin, currentY, colWidth, rowHeight, 'F');
  pdf.rect(margin + colWidth, currentY, colWidth, rowHeight, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Metric', margin + 3, currentY + 5.5);
  pdf.text('Value', margin + colWidth + 3, currentY + 5.5);
  currentY += rowHeight;

  // Rows
  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'normal');
  charStats.forEach(([metric, value], index) => {
    if (index % 2 === 0) {
      pdf.setFillColor(245, 245, 245);
      pdf.rect(margin, currentY, contentWidth, rowHeight, 'F');
    }
    pdf.text(metric, margin + 3, currentY + 5.5);
    pdf.text(value, margin + colWidth + 3, currentY + 5.5);
    currentY += rowHeight;
  });

  currentY += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  const explanation = 'Incorrect characters represent substitutions at the character level; missed characters correspond to omissions; extra characters represent insertions beyond the reference text.';
  const explLines = pdf.splitTextToSize(explanation, contentWidth);
  pdf.text(explLines, margin, currentY);
  currentY += explLines.length * 4 + 8;

  // Word-level statistics
  addSectionTitle('Word-Level Statistics', 12);
  
  const correctWords = testState.wordResults.filter(w => w.status === 'correct').length;
  const incorrectWords = testState.wordResults.filter(w => w.status === 'incorrect').length;
  const missingWords = testState.wordResults.filter(w => w.status === 'missing').length;
  const extraWords = testState.wordResults.filter(w => w.status === 'extra').length;
  const totalWords = testState.referenceWords.length;

  const wordStats = [
    ['Total Words', totalWords.toString()],
    ['Correct Words', correctWords.toString()],
    ['Incorrect Words', incorrectWords.toString()],
    ['Missing Words', missingWords.toString()],
    ['Extra Words', extraWords.toString()],
  ];

  // Header
  pdf.setFillColor(0, 102, 204);
  pdf.rect(margin, currentY, colWidth, rowHeight, 'F');
  pdf.rect(margin + colWidth, currentY, colWidth, rowHeight, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Metric', margin + 3, currentY + 5.5);
  pdf.text('Value', margin + colWidth + 3, currentY + 5.5);
  currentY += rowHeight;

  // Rows
  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'normal');
  wordStats.forEach(([metric, value], index) => {
    checkPageBreak(rowHeight + 5);
    if (index % 2 === 0) {
      pdf.setFillColor(245, 245, 245);
      pdf.rect(margin, currentY, contentWidth, rowHeight, 'F');
    }
    pdf.text(metric, margin + 3, currentY + 5.5);
    pdf.text(value, margin + colWidth + 3, currentY + 5.5);
    currentY += rowHeight;
  });

  currentY += 8;

  // Scoring Methodology
  addSectionTitle('Scoring Methodology', 12);
  
  const scoringWeights = [
    ['Correct Word', `+${testConfig.scoringOptions.correctWord}`],
    ['Missing Word', `${testConfig.scoringOptions.missingWord}`],
    ['Incorrect Spelling', `${testConfig.scoringOptions.incorrectSpelling}`],
    ['Punctuation Error', `${testConfig.scoringOptions.punctuationError}`],
    ['Case Error', `${testConfig.scoringOptions.caseError}`],
  ];

  // Header
  pdf.setFillColor(0, 102, 204);
  pdf.rect(margin, currentY, colWidth, rowHeight, 'F');
  pdf.rect(margin + colWidth, currentY, colWidth, rowHeight, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Component', margin + 3, currentY + 5.5);
  pdf.text('Weight', margin + colWidth + 3, currentY + 5.5);
  currentY += rowHeight;

  // Rows
  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'normal');
  scoringWeights.forEach(([component, weight], index) => {
    if (index % 2 === 0) {
      pdf.setFillColor(245, 245, 245);
      pdf.rect(margin, currentY, contentWidth, rowHeight, 'F');
    }
    pdf.text(component, margin + 3, currentY + 5.5);
    pdf.text(weight, margin + colWidth + 3, currentY + 5.5);
    currentY += rowHeight;
  });

  currentY += 5;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  const scoringDesc = 'The final score is derived by aggregating word-level outcomes using the weights above and then scaling based on both speed (WPM) and accuracy. This produces a single composite metric suitable for comparing performance across sessions.';
  const scoringLines = pdf.splitTextToSize(scoringDesc, contentWidth);
  pdf.text(scoringLines, margin, currentY);
  currentY += scoringLines.length * 4;

  addFooter();
  addPageNumber(2);

  // ============ PAGE 3: TEXT COMPARISON ============
  pdf.addPage();
  currentY = margin;

  addSectionTitle('Text Comparison (For Review)', 16);
  currentY += 3;

  // Reference Text
  addSectionTitle('Reference Passage', 12);
  pdf.setFontSize(8);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0);
  const refLines = pdf.splitTextToSize(testState.referenceText, contentWidth);
  
  refLines.forEach((line: string) => {
    checkPageBreak(5);
    pdf.text(line, margin, currentY);
    currentY += 4;
  });

  currentY += 8;

  // User Input
  addSectionTitle('User Input', 12);
  pdf.setFontSize(8);
  pdf.setFont('courier', 'normal');
  pdf.setTextColor(0, 0, 0);
  const typedLines = pdf.splitTextToSize(testState.typedText || '(No input)', contentWidth);
  
  typedLines.forEach((line: string) => {
    checkPageBreak(5);
    pdf.text(line, margin, currentY);
    currentY += 4;
  });

  addFooter();
  addPageNumber(3);

  // ============ PAGE 4: INTERPRETATION & RECOMMENDATIONS ============
  pdf.addPage();
  currentY = margin;

  addSectionTitle('Performance Interpretation & Recommendations', 16);
  currentY += 3;

  // Performance Interpretation
  addSectionTitle('Performance Interpretation', 12);
  
  let wpmInterpretation = '';
  if (testState.wpm < 20) {
    wpmInterpretation = 'Basic typing proficiency. Recommended to focus on accuracy and fundamental key layout familiarity. Regular practice with simple passages will help build muscle memory.';
  } else if (testState.wpm < 40) {
    wpmInterpretation = 'Developing typing proficiency. Suitable for general use; further practice will improve comfort and speed. Focus on reducing errors while gradually increasing pace.';
  } else if (testState.wpm < 60) {
    wpmInterpretation = 'Functional professional proficiency. Adequate for administrative and technical roles requiring regular typing. Continue practicing to reach advanced levels.';
  } else {
    wpmInterpretation = 'Advanced professional proficiency. Typing speed is well above average for typical office requirements. Maintain this level through regular use.';
  }
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 102, 204);
  pdf.text('Speed Assessment:', margin, currentY);
  currentY += 6;
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(0, 0, 0);
  const wpmLines = pdf.splitTextToSize(wpmInterpretation, contentWidth);
  pdf.text(wpmLines, margin, currentY);
  currentY += wpmLines.length * 5 + 8;

  // Accuracy Commentary
  let accuracyInterpretation = '';
  if (testState.accuracy < 90) {
    accuracyInterpretation = 'Accuracy needs improvement. Focus on typing slowly and correctly rather than rushing. Consistent accuracy practice will build better habits and eventually increase speed naturally.';
  } else if (testState.accuracy < 97) {
    accuracyInterpretation = 'Balanced performance with good accuracy. Continue focusing on maintaining this level while gradually increasing typing speed. This range is suitable for most professional applications.';
  } else {
    accuracyInterpretation = 'Highly reliable character-level accuracy. Excellent attention to detail. This precision is valuable for technical writing, data entry, and professional documentation.';
  }
  
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 102, 204);
  pdf.text('Accuracy Assessment:', margin, currentY);
  currentY += 6;
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(0, 0, 0);
  const accLines = pdf.splitTextToSize(accuracyInterpretation, contentWidth);
  pdf.text(accLines, margin, currentY);
  currentY += accLines.length * 5 + 8;

  // Practice Recommendations
  addSectionTitle('Practice Recommendations', 12);
  
  const recommendations = [
    'Repeat tests on varied passages (technical, narrative, and mixed formats) to improve robustness across different text types.',
    'Focus initial sessions on maintaining accuracy above 95%, then gradually increase speed without sacrificing precision.',
    'Use daily 10-15 minute practice sessions to stabilize muscle memory and build consistent typing habits.',
    'Track your progress over time by saving and comparing PDF reports from multiple sessions to identify improvement trends.',
    'Practice typing common technical terms, keyboard shortcuts, and special characters relevant to your field of work.',
  ];

  pdf.setFontSize(9);
  pdf.setTextColor(0, 0, 0);
  recommendations.forEach((rec, index) => {
    checkPageBreak(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${index + 1}.`, margin, currentY);
    pdf.setFont('helvetica', 'normal');
    const recLines = pdf.splitTextToSize(rec, contentWidth - 8);
    pdf.text(recLines, margin + 6, currentY);
    currentY += recLines.length * 4 + 4;
  });

  currentY += 5;
  
  // Closing Note
  pdf.setFillColor(240, 248, 255);
  pdf.rect(margin, currentY, contentWidth, 25, 'F');
  pdf.setDrawColor(0, 102, 204);
  pdf.rect(margin, currentY, contentWidth, 25);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 102, 204);
  pdf.text('Session Summary', margin + 3, currentY + 6);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(0, 0, 0);
  const summary = `This test session demonstrates ${testState.wpm >= 40 ? 'good' : 'developing'} typing proficiency with ${testState.accuracy >= 95 ? 'excellent' : testState.accuracy >= 90 ? 'good' : 'developing'} accuracy. Continue regular practice to maintain and improve these skills.`;
  const summaryLines = pdf.splitTextToSize(summary, contentWidth - 6);
  pdf.text(summaryLines, margin + 3, currentY + 12);

  addFooter();
  addPageNumber(4);

  // Save the PDF
  const fileName = `SarkariType-Report-${sessionId}.pdf`;
  pdf.save(fileName);
}
