/**
 * PDF Generation Module
 *
 * Generates professional PDF reports of test results
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { TestConfig, TestState } from '../types';

export async function generateResultPDF(
  resultElementId: string,
  testConfig: TestConfig,
  testState: TestState
): Promise<void> {
  const element = document.getElementById(resultElementId);
  if (!element) throw new Error('Result element not found');

  try {
    // Convert HTML element to canvas
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Add header
    pdf.setFontSize(24);
    pdf.setTextColor(0, 102, 204);
    pdf.text('SarkariType - Test Results', 20, 20);

    // Add test info
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);

    const testDate = new Date().toLocaleDateString();
    const testTime = new Date().toLocaleTimeString();

    pdf.text(`Date: ${testDate} ${testTime}`, 20, 35);
    pdf.text(`Duration: ${testState.elapsedSeconds.toFixed(1)} seconds`, 20, 42);
    pdf.text(`WPM: ${testState.wpm}`, 20, 49);
    pdf.text(`Accuracy: ${testState.accuracy.toFixed(1)}%`, 20, 56);
    pdf.text(`Final Score: ${testState.finalScore}`, 20, 63);

    // Add configuration used
    pdf.setFontSize(11);
    pdf.text('Test Configuration:', 20, 73);
    pdf.setFontSize(10);
    pdf.text(`Time Mode: ${testConfig.timeMode}`, 25, 80);
    pdf.text(`Text Source: ${testConfig.textSource}`, 25, 86);
    pdf.text(`Duration: ${testConfig.duration} seconds`, 25, 92);

    // Add the comparison image
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 170;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, 'PNG', 20, 105, imgWidth, imgHeight);

    // Add footer
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by SarkariType - Your Typing Practice Platform', 20, pageHeight - 10);

    // Save the PDF
    const fileName = `sarkaritype-results-${Date.now()}.pdf`;
    pdf.save(fileName);
  } catch (error) {
    console.error('Failed to generate PDF:', error);
    throw new Error('Could not generate PDF. Please try again.');
  }
}
